development:
  adapter: postgresql
  encoding: utf8
  database: borjan_development
  username: root
  password: root
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: borjan_development
  username: root
  password: root
  host: localhost


production:
  adapter: postgresql
  encoding: utf8
  database: borjan_live
  username: borjan_live
  password: Password123.
  host: localhost
