# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b467b32a8deb3d71db6017b492d6f7db5fa321d7f4a94dbc4eeb3fa49f868a8e47898a3c6d99417c58ffa76179f7d8d812fee73ef1f4e9385396aaa138ea3f1
  AWS_BUCKET: "borjan-assets"
  AWS_ACCESS_ID: "AKIAIRK2SNHLP4A6QBOA"
  AWS_ACCESS_SECRET: "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"

staging:
  secret_key_base: ba1271d642956a5e4149ac8b76742bcfda830bea934bd0d83b2da510e03c18b9a0b0daa731d98b16dd6ad5a2e924d16b2e44d03cb052780fa77d413e4ce64ggg
  AWS_BUCKET: "borjan-assets-staging"
  AWS_ACCESS_ID: "AKIAIRK2SNHLP4A6QBOA"
  AWS_ACCESS_SECRET: "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"

test:
  secret_key_base: ba1271d642956a5e4149ac8b76742bcfda830bea934bd0d83b2da510e03c18b9a0b0daa731d98b16dd6ad5a2e924d16b2e44d03cb052780fa77d413e4ce64fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ba1271d642956a5e4149ac8b76742bcfda830bea934bd0d83b2da510e03c18b9a0b0daa731d98b16dd6ad5a2e924d16b2e44d03cb052780fa77d413e4ce64ggg
  AWS_BUCKET: "borjan-assets"
  AWS_ACCESS_ID: "AKIAIRK2SNHLP4A6QBOA"
  AWS_ACCESS_SECRET: "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"
